### ISSUE TITLE
Fault

### ISSUE THREAD

**Issue by HiteshNP** [chottuthejimmy/3rd-sem#8]
you need to add import in the main function of program 6 thats the major error else it won't run as , you're not able to access other classes.

**Comment by chottuthejimmy** [comment]
Ummm , We don't really need to import the files as I have created a sperate package for this program i.e., Program_6_1 . As long as the files we are using are the part of the same package we don't really need to import them . However the method to run these in the command prompt may vary a bit . To run the main file (Program_6.java) in command prompt follow the below procedure : 
![image](https://user-images.githubusercontent.com/108192034/216804059-dc488553-6311-4241-a6a4-f022b86fbea5.png)
 First we need to get into the package , then we need to compile all the files in the package and then checkout of the package and run the main file along with its package

**Comment by HiteshNP** [comment]
Buddy, the problem statement is to use the concept of abstraction, packages, so we need to create 3 packages 

1. For currency converter
2. For distance converter
3. For time converter
4. For main-branch 

Now again, inside these packages, we create the respective classes, and in the main class we import the 3 packages thereby giving access to all the 3 packages and performing all types of conversions.

Check out this simple and easy code-(https://github.com/HiteshNP/OBJECT-ORIENTED-PROGRAMMING-WITH-JAVA/tree/master/program6/src)

Happy Learning and Fun Coding :)
